FROM postgres:9.5-alpine

MAINTAINER Ruben Alcazar <alkazar.r@gmail.com>

ENV DB_NAME database
ENV DB_USER admin
ENV DB_PASS password

ADD setupRemoteConnections.sh /docker-entrypoint-initdb.d/setupRemoteConnections.sh
RUN chmod 755 /docker-entrypoint-initdb.d/setupRemoteConnections.sh

ADD setup-database.sh /docker-entrypoint-initdb.d/
RUN chmod 755 /docker-entrypoint-initdb.d/setup-database.sh

ADD schema.sql /usr
RUN chmod 755 /usr/schema.sql
ADD games.sql /usr
RUN chmod 755 /usr/games.sql
ADD development-data.sql /usr
RUN chmod 755 /usr/development-data.sql

# ================= Docs =================

# === Build the image ===
# docker build -t rubylens-db-image -f Dockerfile.dev .

# === Create the container with our db, user and pass ===
# docker run --name rubylens-db-server -e DB_NAME=rubylens -e DB_USER=rubylens -e DB_PASS=changethis rubylens-db-image

# Enter to db in the container to test all is working
# docker exec -it awesome-db psql --dbname db --username admin
