INSERT INTO games (name) VALUES ('Warhammer 40k');
INSERT INTO games (name) VALUES ('Age of Sigmar/Fantasy');
INSERT INTO games (name) VALUES ('The Horus Heresy');

-- Warhammer 40k
INSERT INTO armies (game_id, name) VALUES (1, 'Adepta Sororitas');
INSERT INTO armies (game_id, name) VALUES (1, 'Space Marines');
INSERT INTO armies (game_id, name) VALUES (1, 'Blood Angels');
INSERT INTO armies (game_id, name) VALUES (1, 'Dark Angels');
INSERT INTO armies (game_id, name) VALUES (1, 'Grey Knights');
INSERT INTO armies (game_id, name) VALUES (1, 'Space Wolves');
INSERT INTO armies (game_id, name) VALUES (1, 'Cult Mechanicus');
INSERT INTO armies (game_id, name) VALUES (1, 'Skitarii');
INSERT INTO armies (game_id, name) VALUES (1, 'Astra Militarum');
INSERT INTO armies (game_id, name) VALUES (1, 'Adeptus Mechanicus');
INSERT INTO armies (game_id, name) VALUES (1, 'Chaos Daemons');
INSERT INTO armies (game_id, name) VALUES (1, 'Chaos Space Marines');
INSERT INTO armies (game_id, name) VALUES (1, 'Chaos Renegades');
INSERT INTO armies (game_id, name) VALUES (1, 'Dark Eldar');
INSERT INTO armies (game_id, name) VALUES (1, 'Death Korps of Krieg');
INSERT INTO armies (game_id, name) VALUES (1, 'Elysian Drop Troops');
INSERT INTO armies (game_id, name) VALUES (1, 'Imperial Navy');
INSERT INTO armies (game_id, name) VALUES (1, 'Red Scorpians');
INSERT INTO armies (game_id, name) VALUES (1, 'Dark Angels');
INSERT INTO armies (game_id, name) VALUES (1, 'Deathwatch');
INSERT INTO armies (game_id, name) VALUES (1, 'Eldar');
INSERT INTO armies (game_id, name) VALUES (1, 'Harlequins');
INSERT INTO armies (game_id, name) VALUES (1, 'Imperial Knights');
INSERT INTO armies (game_id, name) VALUES (1, 'Inquisition');
INSERT INTO armies (game_id, name) VALUES (1, 'Khorne Deamonkin');
INSERT INTO armies (game_id, name) VALUES (1, 'Militarum Tempestus');
INSERT INTO armies (game_id, name) VALUES (1, 'Necrons');
INSERT INTO armies (game_id, name) VALUES (1, 'Officio Assassinorum');
INSERT INTO armies (game_id, name) VALUES (1, 'Orks ');
INSERT INTO armies (game_id, name) VALUES (1, 'Renegade Knights');
INSERT INTO armies (game_id, name) VALUES (1, 'Tau Empire');
INSERT INTO armies (game_id, name) VALUES (1, 'Tyranids');
INSERT INTO armies (game_id, name) VALUES (1, 'Genestealer Cults');

-- Age of Sigmar/Fantasy
INSERT INTO armies (game_id, name) VALUES (2, 'Order- All Armies');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- The Emipre');
INSERT INTO armies (game_id, name) VALUES (2, 'Legion of Azgorh / Chaos Dwarves');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Stormcast Eternals');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Extremis Chamber');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Seraphon');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Sylvaneth');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Fyreslayers');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Devoted of Sigmar');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Free Peoples ');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Collegiate Arcane');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Ironweld Arsenal');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Dispossessed');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Eldritch Council');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Phoenix Temple');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Lion Rangers');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Order Draconis');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Swifthawk Agents');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Scourge Privateers');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Daughters of Khaine');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Darkling Covens ');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Shadowblades');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Order Serpentis');
INSERT INTO armies (game_id, name) VALUES (2, 'Order- Wanderers');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- All Armies ');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Everchosen');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Slaves to Darkness');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Khorne Bloodhound');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Daemons of Khorne');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Daemons of Nurgle');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Hosts of Slaanesh');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Khorne Bloodbound');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Tzeentch Arcanites');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Daemons of Tzeentch');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Nurgle Rotbringers');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Daemons of Chaos');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Brayherds');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Warherds');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Monsters of Chaos');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Chaos Gargants');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Thunderscorn');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Masterclan');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Clans Skryre');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Clans Pestilens');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Clans Eshin');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Clans Verminus');
INSERT INTO armies (game_id, name) VALUES (2, 'Chaos- Clans Moulder');
INSERT INTO armies (game_id, name) VALUES (2, 'Death- All Armies');
INSERT INTO armies (game_id, name) VALUES (2, 'Death- Deathlords');
INSERT INTO armies (game_id, name) VALUES (2, 'Death- Soulblight');
INSERT INTO armies (game_id, name) VALUES (2, 'Death- Deathmages');
INSERT INTO armies (game_id, name) VALUES (2, 'Death- Deadwalkers');
INSERT INTO armies (game_id, name) VALUES (2, 'Death- Deathrattle');
INSERT INTO armies (game_id, name) VALUES (2, 'Death- Flesh-Eater Courts');
INSERT INTO armies (game_id, name) VALUES (2, 'Death- Nighthaunt');
INSERT INTO armies (game_id, name) VALUES (2, 'Destruction- All Armies');
INSERT INTO armies (game_id, name) VALUES (2, 'Destruction- Aleguzzler Gargants');
INSERT INTO armies (game_id, name) VALUES (2, 'Destruction- Beastclaw Raiders');
INSERT INTO armies (game_id, name) VALUES (2, 'Destruction- Bonesplitterz');
INSERT INTO armies (game_id, name) VALUES (2, 'Destruction- Firebellies');
INSERT INTO armies (game_id, name) VALUES (2, 'Destruction- Gitmob Grots');
INSERT INTO armies (game_id, name) VALUES (2, 'Destruction- Greenskinz');
INSERT INTO armies (game_id, name) VALUES (2, 'Destruction- Gutbusters');
INSERT INTO armies (game_id, name) VALUES (2, 'Destruction- Ironjawz');
INSERT INTO armies (game_id, name) VALUES (2, 'Destruction- Maneaters');
INSERT INTO armies (game_id, name) VALUES (2, 'Destruction- Moonclan Grots');
INSERT INTO armies (game_id, name) VALUES (2, 'Destruction- Spiderfang Grots');
INSERT INTO armies (game_id, name) VALUES (2, 'Destruction- Troggoths');

-- The Horus Heresy
INSERT INTO armies (game_id, name) VALUES (3, 'Mechanicum');
INSERT INTO armies (game_id, name) VALUES (3, 'Solar Auxilla');
INSERT INTO armies (game_id, name) VALUES (3, 'Titan Legions');
INSERT INTO armies (game_id, name) VALUES (3, 'Questoris Knights');
INSERT INTO armies (game_id, name) VALUES (3, 'Imperialis Militia & Cults');
INSERT INTO armies (game_id, name) VALUES (3, 'Alpha Legion');
INSERT INTO armies (game_id, name) VALUES (3, 'Blood Angels');
INSERT INTO armies (game_id, name) VALUES (3, 'Dark Angels');
INSERT INTO armies (game_id, name) VALUES (3, 'Death Guard');
INSERT INTO armies (game_id, name) VALUES (3, 'Emperor''s Children');
INSERT INTO armies (game_id, name) VALUES (3, 'Imperial Fists');
INSERT INTO armies (game_id, name) VALUES (3, 'Iron Hands');
INSERT INTO armies (game_id, name) VALUES (3, 'Iron Warriors');
INSERT INTO armies (game_id, name) VALUES (3, 'Night Lords');
INSERT INTO armies (game_id, name) VALUES (3, 'Raven Guard');
INSERT INTO armies (game_id, name) VALUES (3, 'Salamanders');
INSERT INTO armies (game_id, name) VALUES (3, 'Sons of Horus');
INSERT INTO armies (game_id, name) VALUES (3, 'Space Wolves');
INSERT INTO armies (game_id, name) VALUES (3, 'Thousand Sons');
INSERT INTO armies (game_id, name) VALUES (3, 'Ultramarines');
INSERT INTO armies (game_id, name) VALUES (3, 'White Scars');
INSERT INTO armies (game_id, name) VALUES (3, 'Word Bearers');
INSERT INTO armies (game_id, name) VALUES (3, 'World Eaters');
